input {

  beats {

    port => 5044

    host => "0.0.0.0"

  }

}



filter {

  ruby {

    code => "event.set('win_timestamp', event.get('@timestamp').time.strftime('%b %e %H:%M:%S'))"

  }



  if [host][ip][5] {

    mutate { add_field => { "win_ip" => "%{[host][ip][5]}" } }

  } else if [host][ip] and [host][ip][0] {

    mutate { add_field => { "win_ip" => "%{[host][ip][0]}" } }

  } else if [@metadata][ip_address] {

    mutate { add_field => { "win_ip" => "%{[@metadata][ip_address]}" } }

  }



  mutate { add_field => { "win_user" => "N/A" } }



  if [winlog][event_data][TargetUserName] {

    mutate { replace => { "win_user" => "%{[winlog][event_data][TargetUserName]}" } }

  } else if [winlog][event_data][SubjectUserName] {

    mutate { replace => { "win_user" => "%{[winlog][event_data][SubjectUserName]}" } }

  } else if [winlog][user][name] {

    mutate { replace => { "win_user" => "%{[winlog][user][name]}" } }

  }



  mutate { gsub => [ "win_user", "\$", "" ] }



  if [win_user] == "N/A" or [win_user] == "" or [win_user] =~ /%\{/ {

    mutate { replace => { "win_user" => "SYSTEM" } }

  }



  if [winlog][computer_name] {

    mutate { add_field => { "win_host" => "%{[winlog][computer_name]}" } }

  } else if [host][hostname] {

    mutate { add_field => { "win_host" => "%{[host][hostname]}" } }

  } else {

    mutate { add_field => { "win_host" => "%{[host][name]}" } }

  }



  mutate { gsub => [ "message", "[\n\r\t]", " " ] }



  mutate {

    add_field => {

      "formatted_payload" => "<13>%{win_timestamp} %{win_host} AgentDevice=WindowsLog   AgentLogFile=%{[winlog][channel]}       PluginVersion=WC.MSEVEN6.10.1.14.2      Source=%{[winlog][provider_name]}       Computer=%{win_host}    SourceAddress=%{win_host}     User=%{win_user}        usrName=%{win_user}     EventID=%{[winlog][event_id]}   EventIDCode=%{[winlog][event_id]}       EventType=4     EventCategory=1 Message=%{message}"

    }

  }



  mutate {

    remove_field => [ "winlog", "host", "agent", "ecs", "log", "event", "tags", "@version", "win_ip", "win_timestamp", "win_user", "win_host" ]

  }

}



output {

  tcp {

    host => "192.168.30.78"

    port => 514

    codec => line { format => "%{formatted_payload}" }

  }

}
