input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  ruby {
    code => "event.set('win_timestamp', event.get('@timestamp').time.localtime('+07:00').strftime('%b %e %H:%M:%S'))"
  }

  if [winlog][computer_name] {
    mutate { add_field => { "win_host" => "%{[winlog][computer_name]}" } }
  } else if [host][hostname] {
    mutate { add_field => { "win_host" => "%{[host][hostname]}" } }
  } else {
    mutate { add_field => { "win_host" => "%{[host][name]}" } }
  }

  if [winlog][event_data][SubjectUserName] {
    mutate { add_field => { "win_user_raw" => "%{[winlog][event_data][SubjectUserName]}" } }
  } else if [winlog][event_data][TargetUserName] {
    mutate { add_field => { "win_user_raw" => "%{[winlog][event_data][TargetUserName]}" } }
  } else if [winlog][event_data][User] {
    mutate { add_field => { "win_user_raw" => "%{[winlog][event_data][User]}" } }
  } else if [winlog][user][name] {
    mutate { add_field => { "win_user_raw" => "%{[winlog][user][name]}" } }
  } else {
    mutate { add_field => { "win_user_raw" => "SYSTEM" } }
  }

  ruby {
    code => "
      user_raw = event.get('win_user_raw')
      if user_raw
        clean_user = user_raw.split('\\\\').last.delete('$')
        event.set('win_user', clean_user)
      else
        event.set('win_user', 'SYSTEM')
      end
    "
  }

  mutate { gsub => [ "message", "[\n\r\t]", " " ] }

  mutate {
    add_field => {
      "formatted_payload" => "<13>%{win_timestamp} %{win_host} AgentDevice=WindowsLog  AgentLogFile=%{[winlog][channel]}        PluginVersion=WC.MSEVEN6.10.1.14.2      Source=%{[winlog][provider_name]}       Computer=%{win_host}    SourceAddress=%{win_host}      User=%{win_user} usrName=%{win_user}     EventID=%{[winlog][event_id]}   EventIDCode=%{[winlog][event_id]}       EventType=4     EventCategory=1 Message=%{message}"
    }
  }

  mutate {
    remove_field => [ "winlog", "host", "agent", "ecs", "log", "event", "tags", "@version", "win_timestamp", "win_user_raw", "win_user", "win_host" ]
  }
}

output {
  tcp {
    host => "IP_QRADAR"
    port => 514
    codec => line { format => "%{formatted_payload}" }
  }
}
